# Makefile for MinGW running under cygwin

.PHONY: all
all:
	rm -rf hsplzma hsplzma.zip
	mkdir hsplzma
	cp ../hsplzma/hsplzma.dll ../hsplzmax/hsplzmax.dll hsplzma.as hsplzmax.as hsplzma
	7z  a -mx=9 hsplzma.zip hsplzma
